/**
 * Fills the default tank with demo fish so the aquarium has something in it
 * before any real friend shows up (spec AC-01).
 *
 * Two outputs, one generator:
 *   node scripts/seed.js                    write straight into the local SQLite file
 *   node scripts/seed.js --sql --out f.sql  emit SQL to pipe into sqlite3
 *
 * The faces are generated placeholders, not photographs — running this never
 * touches a camera and never invents a person.
 */
import fs from 'node:fs';
import zlib from 'node:zlib';
import { createStore } from '../server/store.js';
import { openSqlite } from '../server/sqlite.js';
import { newId, newInviteCode } from '../server/ids.js';
import { randomLook } from '../shared/fish-variants.js';
import { ACTIVITY_TYPES } from '../shared/activity-text.js';
import { config } from '../server/config.js';
import { statusFor } from '../server/game.js';

const CAST = [
  { name: 'beandog', fullness: 22, skin: [244, 208, 176] },
  { name: 'clare', fullness: 68, skin: [232, 190, 158] },
  { name: 'shahruz', fullness: 91, skin: [198, 152, 112] },
  { name: 'midd', fullness: 47, skin: [166, 122, 88] },
  { name: 'dhof', fullness: 12, skin: [120, 86, 62] },
  { name: 'courtney', fullness: 79, skin: [250, 220, 196] },
];

const DEFAULT_TANK_ID = 'tnk_default';

// --------------------------------------------------------------- local write

async function seedLocal() {
  const db = openSqlite();
  const store = createStore(db);
  const tank = await store.defaultTank();

  const existing = new Set((await store.fishOfTank(tank.id)).map((f) => f.ownerName));
  const wanted = CAST.filter((member) => !existing.has(member.name));

  if (wanted.length === 0) {
    console.log(`"${tank.name}" already has the demo cast (invite: ${tank.invite_code})`);
    db.close();
    return;
  }

  for (const member of wanted) {
    const user = await store.createUser(member.name);
    await store.joinTank(tank.id, user.id);
    const faceAssetId = await store.createFaceAsset(placeholderFacePng(member.skin));
    const fish = await store.createFish({
      tankId: tank.id,
      ownerUserId: user.id,
      faceAssetId,
      ...randomLook(),
    });
    await store.setFullness(fish.id, member.fullness);
    await store.recordActivity({
      tankId: tank.id,
      type: ACTIVITY_TYPES.JOINED,
      actorId: user.id,
      payload: { actorName: member.name },
    });
  }

  const [first, second] = await store.members(tank.id);
  if (first && second) {
    await store.recordActivity({
      tankId: tank.id,
      type: ACTIVITY_TYPES.PRESENCE,
      actorId: first.userId,
      payload: { actorName: first.displayName },
    });
    await store.recordActivity({
      tankId: tank.id,
      type: ACTIVITY_TYPES.FED,
      actorId: second.userId,
      payload: { actorName: second.displayName, targetName: first.displayName },
    });
  }

  console.log(
    `seeded ${wanted.length} fish into "${tank.name}" (invite code: ${tank.invite_code})`,
  );
  console.log(
    `fullness decays ${config.fullness.decayPerHour.toFixed(1)}/hour — ` +
      'the demo fish will get hungry on their own.',
  );
  db.close();
}

// ----------------------------------------------------------------- SQL write

/**
 * Emits the same cast as SQL, for seeding a database you can only reach through
 * a client (`sqlite3 aquarium.db < seed.sql`). Face bytes become `X'..'` blob
 * literals. Everything is `INSERT OR IGNORE`, so running it twice is harmless.
 */
function seedSql(now = Date.now()) {
  const lines = [
    '-- Generated by scripts/seed.js. Demo cast for the default tank.',
    'INSERT OR IGNORE INTO tanks (id, name, invite_code, created_by, created_at)',
    `  VALUES ('${DEFAULT_TANK_ID}', 'the tank', '${newInviteCode()}', NULL, ${now});`,
  ];

  const activity = [];
  let firstFishId = null;
  let clock = now;

  CAST.forEach((member, index) => {
    const userId = newId('usr');
    const faceId = newId('face');
    const fishId = newId('fsh');
    const look = randomLook();
    const hex = Buffer.from(placeholderFacePng(member.skin)).toString('hex');
    if (index === 0) firstFishId = fishId;

    lines.push(
      `INSERT OR IGNORE INTO users (id, display_name, avatar_url, created_at) ` +
        `VALUES ('${userId}', ${quote(member.name)}, NULL, ${now});`,
      `INSERT OR IGNORE INTO tank_members (tank_id, user_id, role, joined_at, last_seen_at) ` +
        `VALUES ('${DEFAULT_TANK_ID}', '${userId}', 'member', ${now}, ${now});`,
      `INSERT OR IGNORE INTO face_assets (id, bytes, created_at) ` +
        `VALUES ('${faceId}', X'${hex}', ${now});`,
      `INSERT OR IGNORE INTO fish (id, tank_id, owner_user_id, face_asset_id, body_variant, ` +
        `fin_variant, body_color, scale, fullness, fullness_updated_at, status, created_at) ` +
        `VALUES ('${fishId}', '${DEFAULT_TANK_ID}', '${userId}', '${faceId}', ` +
        `${quote(look.bodyVariant)}, ${quote(look.finVariant)}, ${quote(look.bodyColor)}, ` +
        `${look.scale}, ${member.fullness}, ${now}, ${quote(statusFor(member.fullness))}, ${now});`,
    );

    activity.push({
      type: ACTIVITY_TYPES.JOINED,
      actorId: userId,
      payload: { actorName: member.name },
    });
  });

  // A couple of extra lines so the activity feed isn't blank on first paint.
  activity.push(
    {
      type: ACTIVITY_TYPES.PRESENCE,
      actorId: null,
      payload: { actorName: CAST[0].name },
    },
    {
      type: ACTIVITY_TYPES.FED,
      actorId: null,
      targetId: firstFishId,
      payload: { actorName: CAST[1].name, targetName: CAST[0].name },
    },
  );

  for (const event of activity) {
    clock += 1;
    lines.push(
      `INSERT OR IGNORE INTO activity_events ` +
        `(id, tank_id, type, actor_id, target_id, payload, created_at) ` +
        `VALUES ('${newId('act')}', '${DEFAULT_TANK_ID}', ${quote(event.type)}, ` +
        `${event.actorId ? `'${event.actorId}'` : 'NULL'}, ` +
        `${event.targetId ? `'${event.targetId}'` : 'NULL'}, ` +
        `${quote(JSON.stringify(event.payload))}, ${clock});`,
    );
  }

  return `${lines.join('\n')}\n`;
}

const quote = (value) => `'${String(value).replace(/'/g, "''")}'`;

// --------------------------------------------------------------------- faces

/**
 * Builds a tiny hand-rolled PNG: a flat skin-tone oval with two dots and a
 * mouth. Enough to read as "a face on a fish" without shipping any real photo
 * or pulling in an image library.
 */
function placeholderFacePng([r, g, b]) {
  const size = 128;
  const raw = Buffer.alloc(size * (size * 4 + 1)); // +1 filter byte per row

  for (let y = 0; y < size; y += 1) {
    const rowStart = y * (size * 4 + 1);
    raw[rowStart] = 0; // filter: none
    for (let x = 0; x < size; x += 1) {
      const i = rowStart + 1 + x * 4;
      const dx = (x - size / 2) / (size * 0.42);
      const dy = (y - size / 2) / (size * 0.5);
      if (dx * dx + dy * dy > 1) continue;

      const eye =
        Math.hypot(x - size * 0.37, y - size * 0.42) < 7 ||
        Math.hypot(x - size * 0.63, y - size * 0.42) < 7;
      const mouth =
        Math.abs(y - size * 0.66) < 3 && Math.abs(x - size * 0.5) < size * 0.14;

      if (eye || mouth) {
        raw[i] = 40;
        raw[i + 1] = 32;
        raw[i + 2] = 30;
      } else {
        // Soft vertical shading so it isn't a dead flat blob.
        const shade = 1 - dy * 0.12;
        raw[i] = clamp8(r * shade);
        raw[i + 1] = clamp8(g * shade);
        raw[i + 2] = clamp8(b * shade);
      }
      raw[i + 3] = 255;
    }
  }

  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0);
  ihdr.writeUInt32BE(size, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // colour type: RGBA

  return new Uint8Array(
    Buffer.concat([
      Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
      pngChunk('IHDR', ihdr),
      pngChunk('IDAT', zlib.deflateSync(raw)),
      pngChunk('IEND', Buffer.alloc(0)),
    ]),
  );
}

function clamp8(value) {
  return Math.max(0, Math.min(255, Math.round(value)));
}

function pngChunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body) >>> 0);
  return Buffer.concat([length, body, crc]);
}

const CRC_TABLE = (() => {
  const table = new Int32Array(256);
  for (let n = 0; n < 256; n += 1) {
    let c = n;
    for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c;
  }
  return table;
})();

function crc32(buffer) {
  let crc = -1;
  for (const byte of buffer) crc = CRC_TABLE[(crc ^ byte) & 0xff] ^ (crc >>> 8);
  return crc ^ -1;
}

// ---------------------------------------------------------------------- main

const args = process.argv.slice(2);

if (args.includes('--sql')) {
  const sql = seedSql();
  const out = args[args.indexOf('--out') + 1];
  if (args.includes('--out') && out) {
    fs.writeFileSync(out, sql);
    console.error(`wrote ${out} (${CAST.length} demo fish)`);
  } else {
    process.stdout.write(sql);
  }
} else {
  await seedLocal();
}
